import { Asset } from './asset';
import { Debt } from './debt';

export class Networth {
    checking: number;
    checkingPercent: number;
    savings: number;
    savingsPercent: number;
    ownHome: boolean;
    homeValues: Asset[];
    homeValuesPercent: number;
    ownCar: boolean;
    carValues: Asset[];
    carValuesPercent: number;
    haveRetirementAccounts: boolean;
    retirementAccountsValues: Asset[];
    retirementAccountsPercent: number;
    haveOtherInvestments: boolean;
    otherInvestmentsValues: Asset[];
    otherInvestmentsPercent: number;
    haveAdditionalAsset: boolean;
    additionalAssetsValues: Asset[];
    additionalAssetPercent: number;
    totalAssets: number;
    totalAssetsPercent: number;
    haveCreditCards: boolean;
    creditCardsValues: Debt[];
    creditCardsPercent: number;
    haveCarLoan: boolean;
    carLoansValues: Debt[];
    carLoansPercent: number;
    haveHomeLoan: boolean;
    homeLoansValues: Debt[];
    homeLoansPercent: number;
    haveSchoolLoans: boolean;
    schoolLoansValues: Debt[];
    schoolLoansPercent: number;
    haveAdditionalDebt: boolean;
    additionalDebtsValues: Debt[];
    additionalDebtPercent: number;
    totalDebt: number;
    totalDebtPercent: number;
    networth: number;
    networthPercent: number;
}
